In [16]:
import pandas as pd
matches_raw = pd.read_csv('/content/drive/MyDrive/projSwing/charting-m-matches.csv')
points_2020s_raw = pd.read_csv('/content/drive/MyDrive/projSwing/charting-m-points-2020s.csv')
points_2010s_raw = pd.read_csv('/content/drive/MyDrive/projSwing/charting-m-points-2010s.csv')

points_raw = pd.concat([points_2010s_raw, points_2020s_raw])

matches_raw.head(10)

/tmp/ipykernel_8447/3685428740.py:3: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  points_2020s_raw = pd.read_csv('/content/drive/MyDrive/projSwing/charting-m-points-2020s.csv')

,match_id,Player 1,Player 2,Pl 1 hand,Pl 2 hand,Date,Tournament,Round,Time,Court,Surface,Umpire,Best of,Final TB?,Charted by
0,20260521-M-Roland_Garros-Q3-Jesper_De_Jong-Mic...,Jesper De Jong,Michael Zheng,R,R,20260521,Roland Garros,Q3,NaN,7,Clay,NaN,3,A,stard54
1,20260517-M-Rome_Masters-F-Casper_Ruud-Jannik_S...,Casper Ruud,Jannik Sinner,R,R,20260517,Rome Masters,F,5pm,Centre,Clay,Renaud Lichtenstein,3,1,Edo
2,20260511-M-Rome_Masters-R16-Rafael_Jodar-Learn...,Rafael Jodar,Learner Tien,R,L,20260511,Rome Masters,R16,NaN,NaN,Clay,NaN,3,1,stard54
3,20260507-M-Rome_Masters-R128-Stefanos_Tsitsipa...,Stefanos Tsitsipas,Tomas Machac,R,R,20260507,Rome Masters,R128,4:35 PM,Paribas,Clay,R. Lichtenstein,3,1,BG
4,20260503-M-Madrid_Masters-F-Jannik_Sinner-Alex...,Jannik Sinner,Alexander Zverev,R,R,20260503,Madrid Masters,F,NaN,NaN,Clay,NaN,3,1,Ludo
5,20260501-M-Madrid_Masters-SF-Arthur_Fils-Janni...,Arthur Fils,Jannik Sinner,R,R,20260501,Madrid Masters,SF,NaN,NaN,Clay,NaN,3,1,Ludo
6,20260430-M-Madrid_Masters-QF-Alexander_Zverev-...,Alexander Zverev,Flavio Cobolli,R,R,20260430,Madrid Masters,QF,9pm,Santana,Clay,Adel Nour,3,1,Edo
7,20260429-M-Madrid_Masters-QF-Rafael_Jodar-Jann...,Rafael Jodar,Jannik Sinner,R,R,20260429,Madrid Masters,QF,NaN,Santana,Clay,NaN,3,1,Ludo
8,20260429-M-Madrid_Masters-QF-Arthur_Fils-Jiri_...,Arthur Fils,Jiri Lehecka,R,R,20260429,Madrid Masters,QF,NaN,NaN,Clay,NaN,3,1,Ludo
9,20260428-M-Madrid_Masters-R16-Casper_Ruud-Stef...,Casper Ruud,Stefanos Tsitsipas,R,R,20260428,Madrid Masters,R16,14:30,Arantxa Sanchez,Clay,Mohamed Lahyani,3,1,Julie DL

In [17]:
points_raw.head(10)

,match_id,Pt,Set1,Set2,Gm1,Gm2,Pts,Gm#,TbSet,Svr,1st,2nd,Notes,PtWinner
0,20191124-M-Davis_Cup_Finals-F-Rafael_Nadal-Den...,1,0,0,0,0.0,0-0,1,True,1,4n,4b1b1b3n@,NaN,1
1,20191124-M-Davis_Cup_Finals-F-Rafael_Nadal-Den...,2,0,0,0,0.0,15-0,1,True,1,5n,5f28f2b1b1b2f3f3d@,NaN,1
2,20191124-M-Davis_Cup_Finals-F-Rafael_Nadal-Den...,3,0,0,0,0.0,30-0,1,True,1,4C,NaN,NaN,1
3,20191124-M-Davis_Cup_Finals-F-Rafael_Nadal-Den...,4,0,0,0,0.0,40-0,1,True,1,4r2d#,NaN,NaN,1
4,20191124-M-Davis_Cup_Finals-F-Rafael_Nadal-Den...,5,0,0,1,0.0,0-0,2,True,2,5d,c4b1b1d!@,NaN,1
5,20191124-M-Davis_Cup_Finals-F-Rafael_Nadal-Den...,6,0,0,1,0.0,0-15,2,True,2,4n,4f38f2b1b1b1b1w@,NaN,1
6,20191124-M-Davis_Cup_Finals-F-Rafael_Nadal-Den...,7,0,0,1,0.0,0-30,2,True,2,6f#,NaN,NaN,2
7,20191124-M-Davis_Cup_Finals-F-Rafael_Nadal-Den...,8,0,0,1,0.0,15-30,2,True,2,4f38f+3f1i^1i3n#,NaN,NaN,2
8,20191124-M-Davis_Cup_Finals-F-Rafael_Nadal-Den...,9,0,0,1,0.0,30-30,2,True,2,4w,6f17f3f3f3n#,NaN,1
9,20191124-M-Davis_Cup_Finals-F-Rafael_Nadal-Den...,10,0,0,1,0.0,30-40,2,True,2,4r17b1m3o3*,NaN,NaN,2

In [18]:
federer_matches = matches_raw[
    matches_raw['Player 1'].str.contains('Federer', case=False, na=False) |
    matches_raw['Player 2'].str.contains('Federer', case=False, na=False)
]
federer_matches.head()

,match_id,Player 1,Player 2,Pl 1 hand,Pl 2 hand,Date,Tournament,Round,Time,Court,Surface,Umpire,Best of,Final TB?,Charted by
2999,20210705-M-Wimbledon-R16-Lorenzo_Sonego-Roger_...,Lorenzo Sonego,Roger Federer,R,R,20210705,Wimbledon,R16,5pm,Centre,Grass,Marija Cicak,5,T,Edo
3003,20210703-M-Wimbledon-R32-Cameron_Norrie-Roger_...,Cameron Norrie,Roger Federer,L,R,20210703,Wimbledon,R32,15:20,Center Court,Grass,Mohamed Lahyani,5,T,Zindaras
3005,20210701-M-Wimbledon-R64-Richard_Gasquet-Roger...,Richard Gasquet,Roger Federer,R,R,20210701,Wimbledon,R64,6pm,Centre,Grass,Richard Haigh,5,0,Edo
3008,20210701-M-Wimbledon-QF-Hubert_Hurkacz-Roger_F...,Hubert Hurkacz,Roger Federer,R,R,20210701,Wimbledon,QF,5pm,Centre,Grass,Nico Helwerth,5,T,Edo
3011,20210629-M-Wimbledon-R128-Roger_Federer-Adrian...,Roger Federer,Adrian Mannarino,R,L,20210629,Wimbledon,R128,5pm,Centre,Grass,James Keothavong,5,1,Edo

In [19]:
federer_match_ids = set(federer_matches['match_id'])
federer_points = points_raw[points_raw['match_id'].isin(federer_match_ids)]
federer_points.head()

,match_id,Pt,Set1,Set2,Gm1,Gm2,Pts,Gm#,TbSet,Svr,1st,2nd,Notes,PtWinner
1292,20191116-M-Tour_Finals-SF-Stefanos_Tsitsipas-R...,1,0,0,0,0.0,0-0,1,True,1,4f1x#,NaN,NaN,1
1293,20191116-M-Tour_Finals-SF-Stefanos_Tsitsipas-R...,2,0,0,0,0.0,15-0,1,True,1,6f17f1f3d@,NaN,NaN,1
1294,20191116-M-Tour_Finals-SF-Stefanos_Tsitsipas-R...,3,0,0,0,0.0,30-0,1,True,1,6b37b1n@,NaN,NaN,2
1295,20191116-M-Tour_Finals-SF-Stefanos_Tsitsipas-R...,4,0,0,0,0.0,30-15,1,True,1,6f38f1f1r#,NaN,NaN,2
1296,20191116-M-Tour_Finals-SF-Stefanos_Tsitsipas-R...,5,0,0,0,0.0,30-30,1,True,1,6s37y3s1*,NaN,NaN,2

In [25]:
import re

FH = set("frvhjulo")
BH = set("bszikymp")
SHOT = re.compile(r"([fbrsvzopuylmhijktq])[+\-=;^]*([0-3])?[789]?[nwdxe!g]*[*#@C]?")

def rally(first, second):
    code = first if isinstance(first, str) else ""
    if re.match(r"^c*[0456]?\+?[nwdxegV!]+$", code):
        code = second if isinstance(second, str) else ""
    code = re.sub(r"^c*[0456]?\+?", "", code) #strip
    out = []
    for t, d in SHOT.findall(code):
        hand = "f" if t in FH else "b" if t in BH else None
        out.append(hand + d if hand and d in ("1", "2", "3") else None)
    return out

labels = ["f1", "f2", "f3", "b1", "b2", "b3"]
matrix = pd.DataFrame(0, index=labels, columns=labels)

for first, second in zip(federer_points["1st"], federer_points["2nd"]):
    shots = rally(first, second)
    for a, b in zip(shots, shots[1:]):
        if a and b:
            matrix.loc[a, b] += 1

matrix.index.name = "last shot"; matrix.columns.name = "next shot (column)"
matrix

next shot (column)    f1    f2    f3    b1    b2     b3
row shot
f1                  8604  6483  7242   696   729    617
f2                  5274  3660  6679  1230  3065   3515
f3                   887   556  1507  4241  7521  12022
b1                  4677  2136  3363   461   289    345
b2                  9158  4206  8871  1904  2707   3384
b3                  3292  1025  5422  6684  6699  15179

In [26]:
prob_matrix = matrix.div(matrix.sum(axis=1), axis=0)
prob_matrix

next shot (column)        f1        f2        f3        b1        b2        b3
row shot
f1                  0.353043  0.266013  0.297156  0.028559  0.029913  0.025317
f2                  0.225163  0.156257  0.285147  0.052512  0.130854  0.150066
f3                  0.033179  0.020797  0.056370  0.158637  0.281327  0.449690
b1                  0.414959  0.189513  0.298376  0.040901  0.025641  0.030610
b2                  0.302944  0.139133  0.293450  0.062984  0.089547  0.111942
b3                  0.085951  0.026762  0.141563  0.174512  0.174904  0.396308